---
- name: Create a VM on VMware vSphere
  hosts: localhost
  gather_facts: no
  collections:
    - vmware.vmware_rest

  tasks:
    - name: Create a VM from template
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "192.168.1.22"
        vcenter_username: "Administrator@vsphere.local"
        vcenter_password: "P@$$w0rd!@^eSk!20!24"  # Consider using Ansible Vault for this
        vcenter_validate_certs: no
        state: present
        name: "Ansible_VMlocaltest3"
        source: "PostgreSQL"  # Use 'source' instead of 'template'
        placement:
          cluster: "C3: DT & BK"
          datastore: "IBM-Storage"
          folder: "/eSkyIT/vm"  # Specify the folder for the VM
        cpu:
          count: 2  # CPU count as a dictionary
        memory:
          size_MiB: 4096  # Memory size as a dictionary
        guest_OS: "RHEL_8_64"  # Set guest OS for RHEL 8
        nics:
          - name: "AliPortGroup"
            ip: "192.168.89.60"
            netmask: "255.255.255.0"
            gateway: "192.168.89.1"
            type: static
        disks:
          - size: 100  # Size in GB
            type: thin
        boot:
          boot_devices:
            - type: "HARD_DRIVE"  # Specify boot device
      delegate_to: localhost

    - name: Power on the VM
      vmware.vmware_rest.vcenter_vm_power:
        vcenter_hostname: "192.168.1.22"
        vcenter_username: "Administrator@vsphere.local"
        vcenter_password: "P@$$w0rd!@^eSk!20!24"  # Consider using Ansible Vault for this
        vcenter_validate_certs: no
        vm: "Ansible_VMlocaltest3"
        state: poweredon  # This will power on the VM
      delegate_to: localhost
