---
- name: Create a VM on VMware vSphere
  hosts: localhost
  gather_facts: no
  collections:
    - vmware.vmware_rest

  tasks:
    - name: Create a VM from template
      vmware.vmware_rest.vcenter_vm_guest_customization:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "Ansible_VMlocaltest"
        template: "PostgreSQL"
        state: poweredon
        folder: "/{{ vcenter_datacenter }}/vm"
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
          - name: "AliPortGroup"
            ip: "192.168.89.55"
            netmask: "255.255.255.0"
            gateway: "192.168.89.1"
            type: static
        disk:
          - size_gb: 100
            type: thin
            datastore: "IBM-Storage"
      delegate_to: localhost