---
- name: Create a VM on VMware vSphere
  hosts: all
  gather_facts: no
  collections:
    - community.vmware

  tasks:
    - name: Create a VM from template
      vmware_guest:
        hostname: "192.168.1.22"
        username: "Administrator@vsphere.local"
        password: "P@$$w0rd!@^eSk!20!24"
        validate_certs: no
        datacenter: "vcsa.eskyit.lab"
        cluster: "eSkyIT"
        name: "Ansible_VMlocaltest"
        template: "PostgreSQL"
        state: poweredon
        folder: "/vcsa.eskyit.lab/vm"
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
          - name: "AliPortGroup"
            ip: "192.168.89.55"
            netmask: "255.255.255.0"
            gateway: "192.168.89.1"
            type: static
        disk:
          - size_gb: 100
            type: thin
            datastore: "IBM-Storage"
      delegate_to: localhost