---
- name: Create a VM on VMware vSphere
  hosts: localhost
  gather_facts: no
  collections:
    - vmware.vmware_rest

  tasks:
    - name: Create a VM from template
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "192.168.1.22"
        vcenter_username: "Administrator@vsphere.local"
        vcenter_password: "P@$$w0rd!@^eSk!20!24"  # Consider using Ansible Vault for this
        validate_certs: no
        datacenter: "eSkyIT"
        cluster: "C3: DT & BK"
        name: "Ansible_VMlocaltest3"
        template: "PostgreSQL"
        state: present  # Change this to 'present'
        folder: "/eSkyIT/vm"
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
          - name: "AliPortGroup"
            ip: "192.168.89.60"
            netmask: "255.255.255.0"
            gateway: "192.168.89.1"
            type: static
        disk:
          - size_gb: 100
            type: thin
            datastore: "IBM-Storage"
      delegate_to: localhost

    - name: Power on the VM
      vmware.vmware_rest.vcenter_vm_power:
        vcenter_hostname: "192.168.1.22"
        vcenter_username: "Administrator@vsphere.local"
        vcenter_password: "P@$$w0rd!@^eSk!20!24"  # Consider using Ansible Vault for this
        validate_certs: no
        vm: "Ansible_VMlocaltest3"
        state: poweredon  # This will power on the VM
      delegate_to: localhost
